In [1]:
%%time
a_nswer = 1
i = 1
while i <= 10:
    a_nswer = a_nswer * i
    i = i + 1

print('The factorial of 100 is: {}'.format(a_nswer))

The factorial of 100 is: 3628800
CPU times: total: 0 ns
Wall time: 0 ns


In [3]:
i = 1
result = 1

while i<=100:
    result = result * i
    if i == 42:
        print('magic number 42 reached! stop execute..')
        break
    i += 1

print('i:', i)
print('result', result)
    


magic number 42 reached! stop execute..
i: 42
result 1405006117752879898543142606244511569936384000000000


In [2]:
i = 1
result = 1
while i < 20:
    i += 1
    if i % 2 == 0:
        print('skipping {} '.format(i))
        continue
    print('multiplying with {}.'.format(i))
    result = result * i

print('i:', i)
print('result:', result)
    

skipping 2 
multiplying with 3.
skipping 4 
multiplying with 5.
skipping 6 
multiplying with 7.
skipping 8 
multiplying with 9.
skipping 10 
multiplying with 11.
skipping 12 
multiplying with 13.
skipping 14 
multiplying with 15.
skipping 16 
multiplying with 17.
skipping 18 
multiplying with 19.
skipping 20 
i: 20
result: 654729075


In [7]:
name = "Aiza"
print("Morning, %s!" % name)

Morning, Aiza!


In [8]:
name = "Muhammad"
print("Salam, %s!" % name)

Salam, Muhammad!


In [9]:
name = "Officer"
print("Good day, %s!" % name)

Good day, Officer!


In [10]:
name = "Tolani"
print("Where have you been %s!" % name)


Where have you been Tolani!


In [11]:
name = "Muhammad"
print("Where were you, I have been looking for you %s" % name)

Where were you, I have been looking for you Muhammad


In [1]:
name = "Lade"
income = 65000
age = 33
print("%s is %d years old, earning %s as income!" % (name,age,income))

Lade is 33 years old, earning 65000 as income!


In [2]:
name = "John"
age = 23
print("%s is %d years old." % (name, age))

John is 23 years old.


In [3]:
name = "Joel"
age = 33
print("%s is %d years old." % (name,age))

Joel is 33 years old.


In [4]:
name = "Wale"
salary = 30000
print("%s is earning %d dirahm monthly." % (name, salary))


Wale is earning 30000 dirahm monthly.


In [5]:
name = "Abdul Hamid"
overtime = 70000
salary = 120000

print("%s is getting %d dirahm overtime monthly!" %(name,overtime))


Abdul Hamid is getting 70000 dirahm overtime monthly!


In [6]:
name = "Lade"
income = 65000
age = 33
print("%s is %d years old, earning %s as income!" % (name,age,income))

Lade is 33 years old, earning 65000 as income!


####### Any object which is not a string can be formatted using the %s operator as well. The string which returns from the "repr" method of that object is formatted as the string. For example:

In [12]:
mylist = [1,2,3,4,5]
print("A list: %s" % mylist)

A list: [1, 2, 3, 4, 5]


In [17]:
evenlist = [2,4,6,8,10]
print("A list of even number %s" % evenlist)

A list of even number [2, 4, 6, 8, 10]


In [ ]:
##### Here are some basic argument specifiers you should know:

%s - String (or any object with a string representation, like numbers)

%d - Integers

%f - Floating point numbers

%.<number of digits>f - Floating point numbers with a fixed amount of digits to the right of the dot.

%x/%X - Integers in hex representation (lowercase/uppercase)

###### Exercise
You will need to write a format string which prints out the data using the following syntax: Hello John Doe. Your current balance is $53.44.

In [18]:
data = ("John", "Doe", 53.44)
format_string = "Hello %s %s. Your current balance is $%s."

print(format_string % data)

Hello John Doe. Your current balance is $53.44.


In [6]:
language = "C"
if language == "python":
    print('language is python')
    
elif language == "java":
    print('java script')
    
elif language == "C":
    print('the programming language is C')
else:
    print('no match')

the programming language is C


In [11]:
first_child = "muhammad"
if first_child == "abdulrahman":
    print('That\'s correct' )
elif first_child == "aiza":
    print('certainly')
elif first_child == "muhammad":
    print('you may be wright but am not sure')
else:
    print('False info')

you may be wright but am not sure


In [13]:
first_child = "abdulrahman"
male_child = False

if first_child == "abdulrahman" and male_child == True:
    print('absolutely')
else:
    print('wrong info')

wrong info


In [17]:
my_child = "amin"
morolayo = True

if my_child == "aiza" or morolayo == True:
    print('fun fact')
else:
    print('park well')

fun fact


In [20]:
my_child = "aiza"
morolayo = False
if not morolayo:
    print('authentic')
else:
    print('bad info')

authentic


In [25]:
condition = ""

if condition:
    print('evaluate to true')
else:
    print('evaluate to false')

evaluate to false


In [26]:
greetings = 'compliment of the season\'s to you my love'
print(greetings)

compliment of the season's to you my love


In [30]:
home_lyrics = """ Home my home!!!, 
when shall i see my home?, when shall i see my native friend
and my sister's children, 
I will never forget my home.

"""
print(home_lyrics)


 Home my home!!!, 
when shall i see my home?, when shall i see my native friend
and my sister's children, 
I will never forget my home.




In [31]:
salute = 'your majesty'
print(salute[:4])

your


In [32]:
print(salute[5:])

majesty


In [33]:
print(salute[-7:])

majesty


In [34]:
my_list = [0,1,2,3,4,5,6,7,8,9]
         # 0,1,2,3,4,5,6,7,8,9
         #-10               -1  
    

In [35]:
print(my_list[:])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [37]:
print(my_list[1:6:2])

[1, 3, 5]


In [38]:
print(my_list[2:9:2])

[2, 4, 6, 8]


In [39]:
#string

mac = 'h1'
donald = 'get on the line'

details = '<{0}> {1} </{0}>'.format(mac, donald)
print(details)

<h1> get on the line </h1>


In [41]:
staff = {'name':'joel', 'gender':'male', 'dept':'logistics', 'age':35, 'doj':'13th-sept-23'}
details = "My name is {0[name]}, I am {0[gender]}, I work in {0[dept]}, I am {0[age]} years old and I joined the compay on {0[doj]}.".format(staff)
print(details)

My name is joel, I am male, I work in logistics, I am 35 years old and I joined the compay on 13th-sept-23.


In [42]:
staff = {'name':'joel', 'gender':'male', 'dept':'logistics', 'age':35, 'doj':'13th-sept-23'}
info = ['joel', 'male', 'logistics', 35, '13th-sept-23']
details = "My name is {0[0]}, I am {0[1]}, I work in {0[2]}, I am {0[3]} years old and i joined the company on {0[4]}.".format(info)
print(details)

My name is joel, I am male, I work in logistics, I am 35 years old and i joined the company on 13th-sept-23.


In [43]:
employee = {'name':'jenny', 'age': 23, 'gender':'female'}
details = "My name is {name}, I am {age} years old and I am {gender}.".format(**employee)
print(details)

My name is jenny, I am 23 years old and I am female.


In [44]:
# Numbers range

for i in range(10):
    details = 'The value is {}'.format(i)
    print(details)

The value is 0
The value is 1
The value is 2
The value is 3
The value is 4
The value is 5
The value is 6
The value is 7
The value is 8
The value is 9


In [47]:
for i in range(1,11):
    info = 'The data is {}'.format(i)
    print(info)

The data is 1
The data is 2
The data is 3
The data is 4
The data is 5
The data is 6
The data is 7
The data is 8
The data is 9
The data is 10


In [ ]:
###### convert to decimal places

In [49]:
for i in range(1,6):
    info = 'number is in two decimal point {:02}'.format(i)
    print(info)

number is in two decimal point 01
number is in two decimal point 02
number is in two decimal point 03
number is in two decimal point 04
number is in two decimal point 05


In [51]:
#### convert float number to .. decimal place

pi = 3.45666
detail = 'this is {:.3f}'.format(pi)
print(detail)

this is 3.457


In [57]:
import datetime
my_date = datetime.datetime(1981,12,27,12,30)
period = '{:%B,%d,%Y}'.format(my_date)
print(period)

December,27,1981


In [58]:
greetings = "good morning"
print(greetings)

good morning


In [59]:
greetings = "good morning"
print(greetings.upper())

GOOD MORNING


In [60]:
greetings = "good morning"
print(greetings.lower())

good morning


In [61]:
##replace.
greetings = "good morning"
print(greetings.replace('good', 'wonderful'))


wonderful morning


In [64]:
greetings = "good morning"
print(greetings.replace('morning', 'afternoon').upper())

GOOD AFTERNOON


In [ ]:
#### concatenate

In [68]:
greetings = "Hello"
name = "Muhammad"

details = greetings + ' ' + name + '! welcome'
print(details)

Hello Muhammad! welcome


In [71]:
details = '{} {}'.format(greetings,name)
print(details)

Hello Muhammad


In [74]:
details = f'{greetings} {name}'
print(details)

Hello Muhammad


In [78]:
message = "lovely day"
name = "Abdulrahman"

details = f'do have a {message.upper()} at work {name.upper()}'
print(details)

do have a LOVELY DAY at work ABDULRAHMAN


In [79]:
num = 3
num += 4
print(num)

7


In [80]:
num = 2
num *= 5
print(num)

10


In [81]:
print(abs(-13))

13


In [85]:
print(round(4.656, 3))

4.656


In [ ]:
### casting

In [87]:
num_1 = '3000'
num_2 = '1500'

print(int(num_1) + int(num_2))

4500


In [88]:
num_1 = '3000'
num_2 = '1500'

num_1 = int(num_1)
num_2 = int(num_2)

print(num_1 + num_2)

4500


In [90]:
####### TO SORT THE LIST THAT CONTAINS NUMBERS & VALUES(TO SORT VALUES IN DESC OR BOTH )
courses = ['physics','maths','chem','english']
nums = [1,3,2,6,5,4,7,9,8]

courses.sort()
nums.sort()

print(courses)
print(nums)

['chem', 'english', 'maths', 'physics']
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [91]:
####### TO SORT THE LIST THAT CONTAINS NUMBERS & VALUES(TO SORT VALUES IN DESC OR BOTH )
courses = ['physics','maths','chem','english']
nums = [1,3,2,6,5,4,7,9,8]

courses.sort(reverse=True)
nums.sort(reverse=True)

print(courses)
print(nums)

['physics', 'maths', 'english', 'chem']
[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [92]:
##### To add list from another list to original list use EXTEND (it's useful when adding multiple list)

courses = ['physics','maths','chem','english']
courses_2 = ['commerce','literature']

courses.extend(courses_2)
print(courses)

['physics', 'maths', 'chem', 'english', 'commerce', 'literature']


In [94]:
#### To add into particular place in the list - use INSERT and then mention location

courses = ['physics','maths','chem','english']

courses.insert(1,'literature')
print(courses)

['physics', 'literature', 'maths', 'chem', 'english']


In [95]:
courses.append('geo')
print(courses)

['physics', 'literature', 'maths', 'chem', 'english', 'geo']


In [96]:
courses.pop()
print(courses)

['physics', 'literature', 'maths', 'chem', 'english']


In [99]:
courses.remove('chem')
print(courses)

['physics', 'maths', 'english']


In [100]:
##### TO GET SORTED VERSION OF THE LISTS WITHOUT ALTERING THE ORIGINAL LISTS.
courses = ['physics','maths','chem','english']
nums = [1,3,2,6,5,4,7,9,8]

courses = sorted(courses)
nums = sorted(nums)
print(courses)
print(nums)

['chem', 'english', 'maths', 'physics']
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [101]:
##### MIN,MAX,SUM
nums = [1,3,2,6,5,4,7,9,8]
print(sum(nums))


45


In [103]:
print(min(nums))

1


In [104]:
print(max(nums))

9


In [106]:
####### To search for index of the particular value in the list
courses = ['physics','maths','chem','english']

print(courses.index('chem'))

2


In [108]:
##### To search if the values are in the list
courses = ['physics','maths','chem','english']
print('maths'in courses)

True


In [109]:
print('bio' in courses)

False


In [111]:
##### To loop through values of the list by using for loop
courses = ['physics','maths','chem','english']

for i in courses:
    print(i)

physics
maths
chem
english


In [112]:
for course in courses:
    print(course)

physics
maths
chem
english


In [118]:
##### To loop through values of the list by using for loop and have index...
courses = ['physics','maths','chem','english']

for index, course in enumerate(courses):
    print(index, course)


0 physics
1 maths
2 chem
3 english


In [119]:
##### To loop through values of the list by using for loop and have index start from 1
courses = ['physics','maths','chem','english']

for index, course in enumerate(courses, start=1):
    print(index, course)


1 physics
2 maths
3 chem
4 english


In [120]:
#### TO TURN THE LIST INTO STRING SEPERATED BY COMA
courses = ['physics','maths','chem','english']

courses_str = ', '.join(courses)
print(courses_str)


physics, maths, chem, english


In [ ]:
##### TO REVERSE STRING BACK TO THE LIST

In [124]:
new_courses = courses_str.split(', ')
print(new_courses)

['physics', 'maths', 'chem', 'english']


In [122]:
#### TO TURN THE LIST INTO STRING SEPERATED BY (-)
fruits = ['apple','mango','grapes','berry']
fruits_str = ' - '.join(fruits)
print(fruits_str)

apple - mango - grapes - berry


In [ ]:
##### TO REVERSE STRING BACK TO THE LIST

In [123]:
new_list = fruits_str.split(' - ')
print(new_list)

['apple', 'mango', 'grapes', 'berry']


In [125]:
list_1 = ['math','chem','physics','eng','geo']
list_2 = list_1

print(list_1)
print(list_2)

['math', 'chem', 'physics', 'eng', 'geo']
['math', 'chem', 'physics', 'eng', 'geo']


In [126]:
list_1[3] = 'econ'
print(list_1)
print(list_2)


['math', 'chem', 'physics', 'econ', 'geo']
['math', 'chem', 'physics', 'econ', 'geo']


In [132]:
a_level = {'maths','eng','phy','chem','geo'}
o_level = {'maths','eng','bio','commerce','art'}

In [133]:
print(a_level.intersection(o_level))


{'maths', 'eng'}


In [137]:
print(a_level.difference(o_level))

{'phy', 'geo', 'chem'}


In [138]:
print(o_level.difference(a_level))

{'commerce', 'art', 'bio'}


In [136]:
fruits = {'apple','mango','grapes','berry'}
courses = {'physics','maths','chem','english','mango','apple'}
print(fruits.intersection(courses))

{'mango', 'apple'}


In [139]:
a_level = {'maths','eng','phy','chem','geo'}
o_level = {'maths','eng','bio','commerce','art'}

print(a_level.union(o_level))

{'commerce', 'bio', 'phy', 'chem', 'art', 'geo', 'maths', 'eng'}


In [142]:
#### for loops
nums = [1,2,3,4,5,6,7]

for num in nums:
    if num == 6:
        print('great')
        break
    print(num)

1
2
3
4
5
great


In [148]:
nums = [1,3,2,6,5,4,7,9,8]
nums.sort()
for num in nums:
    if num == 9:
        print('excellent')
        break
    print(num) 

1
2
3
4
5
6
7
8
excellent


In [149]:
nums = [1,3,2,6,5,4,7,9,8]
nums.sort()
for num in nums:
    if num == 8:
        print('bravo')
        continue
    print(num)

1
2
3
4
5
6
7
bravo
9


In [152]:
## loop within a loop
nums = [1,2,3,4,5,6]
for num in nums:
    for alphabet in 'ab':
        
        print(num,alphabet)
        

1 a
1 b
2 a
2 b
3 a
3 b
4 a
4 b
5 a
5 b
6 a
6 b


In [156]:
##### TO RUN THROUGH A LOOP 10-times (range key-word is require)
for i in range (10):
    print(i)


0
1
2
3
4
5
6
7
8
9


In [157]:
for i in range(1, 8):
    print(i)

1
2
3
4
5
6
7


In [168]:
#### while loop

x = 0
while x <= 10:
    print(x)
    x += 2

0
2
4
6
8
10


In [4]:
m = 1

while m <= 16:
    print(m)
    m *= 2
    

1
2
4
8
16


In [8]:
##### Function

def greetings():
    print('we are the world, we are the children!')

greetings()

we are the world, we are the children!


In [9]:
def greetings():
    return'we are the world, we are the children!'

print(greetings())

we are the world, we are the children!


In [10]:
def salutation():
    return 'life goes on!'

print(salutation())

life goes on!


In [13]:
#### change  to upper or lower

def salutation():
    return 'life goes on!'

print(salutation().upper())

LIFE GOES ON!


In [15]:
def greetings():
    return'we are the world, we are the children!'

print(greetings().upper())

WE ARE THE WORLD, WE ARE THE CHILDREN!


In [22]:
###### HOW TO PASS ARGUMENT TO THE FUNCTION
def greetings(salute):
    return'{} your excellency'.format(salute)
print(greetings('Good morning'))

Good morning your excellency


In [24]:
def greetings(message):
    return '{} we are the chidren!'.format(message)

print(greetings('we are the world,'))

we are the world, we are the chidren!


In [26]:
def greetings(mine):
    return '{} at work sweet heart'.format(mine)

print(greetings('do have a wonderful day').upper())

DO HAVE A WONDERFUL DAY AT WORK SWEET HEART


In [31]:
def greetings(sweetie, name = 'adeola'):
    return '{} {} thinking about you my love'.format(sweetie, name)

print(greetings('I can\'t just stop'))

I can't just stop adeola thinking about you my love


In [34]:
def greetings(eulogy, name = 'romola'):
    return '{} {} and the love of my live.'.format(eulogy, name)

print(greetings('You are the apple of my eyes'))

You are the apple of my eyes romola and the love of my live.


In [39]:
def employee(*args, **kwargs):
    print(args)
    print(kwargs)
    
employee('female','married', name='hope',age=30, dept='logistics')

('female', 'married')
{'name': 'hope', 'age': 30, 'dept': 'logistics'}


In [45]:
def empl_inf(*args, **kwargs):
    print(args)
    print(kwargs)
    
a_level = ['maths','eng','phy','chem','geo']
o_level = {'maths':'mat','eng':'en','bio':'bi','commerce':'com','art':'ar'}

print(empl_inf(*a_level, **o_level))


('maths', 'eng', 'phy', 'chem', 'geo')
{'maths': 'mat', 'eng': 'en', 'bio': 'bi', 'commerce': 'com', 'art': 'ar'}
None


In [ ]:
##### numpy

In [46]:
import numpy as np

In [48]:
d = np.array([[1,2,3,4,5,6],[7,8,9,1,2,3]])
print(d)

[[1 2 3 4 5 6]
 [7 8 9 1 2 3]]


In [54]:
d[:,1]


array([2, 8])

In [56]:
d[0:,3]

array([4, 1])

In [58]:
d[1,:]

array([7, 8, 9, 1, 2, 3])

In [59]:
d[0,2:6:1]

array([3, 4, 5, 6])

In [62]:
d[:,3] = [7,5]
print(d)

[[1 2 3 7 5 6]
 [7 8 9 5 2 3]]


In [64]:
d[1,4] = 23
print(d)

[[ 1  2  3  7  5  6]
 [ 7  8  9  5 23  3]]


In [67]:
e = np.array([[[3,2],[3,4]],[[3,5],[4,3]]])
print(e)

[[[3 2]
  [3 4]]

 [[3 5]
  [4 3]]]


In [68]:
f = np.array([[[2,4],[3,4]],[[2,5],[4,6]]])
print(f)

[[[2 4]
  [3 4]]

 [[2 5]
  [4 6]]]


In [70]:
f[0,1,1]

4

In [71]:
f[1,0,0]

2

In [72]:
f[:,0,:]

array([[2, 4],
       [2, 5]])

In [75]:
f[:,1,:] = [[8,8],[4,5]]

In [76]:
print(f)

[[[2 4]
  [8 8]]

 [[2 5]
  [4 5]]]


In [4]:
people = {'Firstname':['Jack','Ben','Gin','Husk'],
         'Lastname':['Rob','Aflex','Rob','Rob'],
         'Email':['jack@gmail.com','ben@gmail.com','gin@gmail.com','husk1@gmail.com']
    
    
    
    
}

In [5]:
people['Email']

['jack@gmail.com', 'ben@gmail.com', 'gin@gmail.com', 'husk1@gmail.com']

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(people)

In [6]:
df

Firstname Lastname            Email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

In [13]:
df['Email']  #### This method to access value from dataframe is much better and safe from getting error

0     jack@gmail.com
1      ben@gmail.com
2      gin@gmail.com
3    husk1@gmail.com
Name: Email, dtype: object

In [15]:
df.Email     ### dot "." notation can also be used to access values in the dataframe

0     jack@gmail.com
1      ben@gmail.com
2      gin@gmail.com
3    husk1@gmail.com
Name: Email, dtype: object

In [14]:
type(df['Email'])   ### a series is accessing a single column or row.

pandas.core.series.Series

In [ ]:
### To rename the column.



In [7]:
#### TO ACCESS MULTIPLE COLUMN: note, this no longer a series cos it access multiple rows and column
##### ### this is another dataframe. this is like a filter with  specific columns or multiple column.

df[['Lastname', 'Email']]  


Lastname            Email
0      Rob   jack@gmail.com
1    Aflex    ben@gmail.com
2      Rob    gin@gmail.com
3      Rob  husk1@gmail.com

In [17]:
#### if you have alot of columns and you want to see all of them easily then we can rap the column
### specificly by saying

df.columns

Index(['Firstname', 'Lastname', 'Email'], dtype='object')

In [ ]:
#### then how can we get rows? we can get rows by using "loc" and "iloc"
### iloc allow us to access rows by integer location. iloc-stands for (index)integer location.

In [18]:
df.iloc[0]    ### To get the first row because our integer location i.e (index) started from "0". it returns
              ### the series of the first row that contains the data.

Firstname              Jack
Lastname                Rob
Email        jack@gmail.com
Name: 0, dtype: object

In [8]:
#### To select multiple rows

df.iloc[[0,1,2]]

Firstname Lastname           Email
0      Jack      Rob  jack@gmail.com
1       Ben    Aflex   ben@gmail.com
2       Gin      Rob   gin@gmail.com

In [20]:
### with these iloc and loc indexes, we can also select columns as well. that will be the 
### second value that we will pass into to the iloc list. With "iloc" & "loc" functions, we can think
### of rows and columns

df.iloc[[0,1,2],2]   #### if i needed the email of the these rows that i pass in.
                     ####('remember "Fistname/First column is 0"') therefore "2" is email.

0    jack@gmail.com
1     ben@gmail.com
2     gin@gmail.com
Name: Email, dtype: object

In [ ]:
#### Let's look into "loc". we will be searching by label.

In [9]:
df

Firstname Lastname            Email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

In [22]:
df.loc[0]

Firstname              Jack
Lastname                Rob
Email        jack@gmail.com
Name: 0, dtype: object

In [10]:
df.loc[[0,1,2]]

Firstname Lastname           Email
0      Jack      Rob  jack@gmail.com
1       Ben    Aflex   ben@gmail.com
2       Gin      Rob   gin@gmail.com

In [27]:
df.loc[[0,1,2], 'Email']

0    jack@gmail.com
1     ben@gmail.com
2     gin@gmail.com
Name: Email, dtype: object

In [11]:
df.loc[[0,1,2], ['Email','Lastname']]

Email Lastname
0  jack@gmail.com      Rob
1   ben@gmail.com    Aflex
2   gin@gmail.com      Rob

###### Indexes - How to Set, Reset, and Use

In [29]:
df = pd.DataFrame(people)

In [12]:
df

Firstname Lastname            Email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

In [31]:
### To access only email addresses.

df['Email']

0     jack@gmail.com
1      ben@gmail.com
2      gin@gmail.com
3    husk1@gmail.com
Name: Email, dtype: object

In [13]:
#### To set these emails addresses as an index for this data frame:

df.set_index('Email')

Firstname Lastname
Email                             
jack@gmail.com       Jack      Rob
ben@gmail.com         Ben    Aflex
gin@gmail.com         Gin      Rob
husk1@gmail.com      Husk      Rob

In [14]:
df      ### as you can see, the original dataframe is not being affected.

Firstname Lastname            Email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

In [15]:
#### But if we really want to modify the dataframe and if we want the changes to really have impact.

df.set_index('Email', inplace=True)

In [16]:
df   ### Now as you can see, our dataframe has change

Firstname Lastname
Email                             
jack@gmail.com       Jack      Rob
ben@gmail.com         Ben    Aflex
gin@gmail.com         Gin      Rob
husk1@gmail.com      Husk      Rob

In [36]:
df.index

Index(['jack@gmail.com', 'ben@gmail.com', 'gin@gmail.com', 'husk1@gmail.com'], dtype='object', name='Email')

In [39]:
df.loc['jack@gmail.com', 'Lastname']

'Rob'

In [17]:
df.loc['ben@gmail.com', 'Lastname']

'Aflex'

In [41]:
df.loc[0]     ### because the index has change to "email address" (label) but it can still be accessed
              ### by using "iloc"

KeyError: 0

In [42]:
df.iloc[0]

Firstname    Jack
Lastname      Rob
Name: jack@gmail.com, dtype: object

In [18]:
df

Firstname Lastname
Email                             
jack@gmail.com       Jack      Rob
ben@gmail.com         Ben    Aflex
gin@gmail.com         Gin      Rob
husk1@gmail.com      Husk      Rob

#### How to "reset the index" from label to integer if you accidently set the index to label

In [15]:
df.reset_index(inplace=True)

In [17]:
df

level_0  index Firstname Lastname            Email
0        0      0      Jack      Rob   jack@gmail.com
1        1      1       Ben    Aflex    ben@gmail.com
2        2      2       Gin      Rob    gin@gmail.com
3        3      3      Husk      Rob  husk1@gmail.com

#### Filtering - Using Conditionals to Filter Rows and Columns

In [22]:
df['Lastname'] == 'Rob'

0     True
1    False
2     True
3     True
Name: Lastname, dtype: bool

In [10]:
filt = (df['Lastname'] == 'Rob')

In [11]:
df[filt]

index Firstname Lastname            Email
0      0      Jack      Rob   jack@gmail.com
2      2       Gin      Rob    gin@gmail.com
3      3      Husk      Rob  husk1@gmail.com

In [14]:
df.loc[filt]

index Firstname Lastname            Email
0      0      Jack      Rob   jack@gmail.com
2      2       Gin      Rob    gin@gmail.com
3      3      Husk      Rob  husk1@gmail.com

In [ ]:
#### To filter the email....

In [18]:
df.loc[filt, 'Email']

0     jack@gmail.com
2      gin@gmail.com
3    husk1@gmail.com
Name: Email, dtype: object

In [ ]:
#### "&" which stands for (AND), "|" which stand for (OR) can also be used to FILTER.

In [25]:
filt= (df['Lastname'] == 'Rob') & (df['Firstname'] == 'Gin')

In [26]:
df.loc[filt,'Email']


2    gin@gmail.com
Name: Email, dtype: object

In [ ]:
##### To filter using "|" (OR) function

In [27]:
filt = (df['Lastname'] == 'Rob') | (df['Firstname'] == 'Husk')

In [29]:
df.loc[filt, 'Email']

0     jack@gmail.com
2      gin@gmail.com
3    husk1@gmail.com
Name: Email, dtype: object

In [ ]:
#### TO GET OPPOSITE RESULT OF THE ABOVE . JUST PUT "~" (TIL) AT THE BACK OF "filt"

In [30]:
filt = (df['Lastname'] == 'Rob') | (df['Firstname'] == 'Husk')

In [31]:
df.loc[~filt, 'Email']

1    ben@gmail.com
Name: Email, dtype: object

In [ ]:
 ##### Updating Rows and Columns - Modifying Data Within DataFrames

In [45]:
import pandas as pd

In [46]:
df = pd.DataFrame(people)

In [47]:
df

Firstname Lastname            Email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

In [48]:
### To check the columns

df.columns

Index(['Firstname', 'Lastname', 'Email'], dtype='object')

In [36]:
#### To rename the column

df.columns = ['First_name','Last_name', 'Email']

In [37]:
df.columns

Index(['First_name', 'Last_name', 'Email'], dtype='object')

In [38]:
### check data frame if there is changes

df

First_name Last_name            Email
0       Jack       Rob   jack@gmail.com
1        Ben     Aflex    ben@gmail.com
2        Gin       Rob    gin@gmail.com
3       Husk       Rob  husk1@gmail.com

##### To change column name from upper to lover or vice-versa or column have spaces and you want to replace
#### spaces with "_" (under-score)

In [49]:
df.columns = [x.upper() for x in df.columns]

In [51]:
df

FIRSTNAME LASTNAME            EMAIL
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

In [67]:
df.columns = ['FIRST NAME','LAST NAME','EMAIL']

In [68]:
df

FIRST NAME LAST NAME            EMAIL
0       Jack       Rob   jack@gmail.com
1        Ben     Aflex    ben@gmail.com
2        Gin       Rob    gin@gmail.com
3       Husk       Rob  husk1@gmail.com

In [ ]:
#### To reduce spaces and replace them with "_" under-score (Note, you cannot use dot (.) notation if there is a space between your variables)

In [69]:
df.columns = df.columns.str.replace(' ', '_')

In [70]:
df

FIRST_NAME LAST_NAME            EMAIL
0       Jack       Rob   jack@gmail.com
1        Ben     Aflex    ben@gmail.com
2        Gin       Rob    gin@gmail.com
3       Husk       Rob  husk1@gmail.com

In [ ]:
#### To change to lower case

In [71]:
df.columns = [x.lower() for x in df.columns]

In [72]:
df

first_name last_name            email
0       Jack       Rob   jack@gmail.com
1        Ben     Aflex    ben@gmail.com
2        Gin       Rob    gin@gmail.com
3       Husk       Rob  husk1@gmail.com

In [ ]:
#### what if i want to change some column, not every column.
#### for example i want to return firstname and lastname to what they were before

In [73]:
df.rename(columns={'first_name':'Firstname', 'last_name':'Lastname'}, inplace=True)

In [74]:
df

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

#### updating rows

In [75]:
#to update a single value, for expample.change the lastname of "Ben Aflex" in above column, i.e index 1

df.loc[1]

Firstname              Ben
Lastname             Aflex
email        ben@gmail.com
Name: 1, dtype: object

In [76]:
df.loc[1] = ['Ben','Smith', 'smith@gmail.com']

In [77]:
df

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Smith  smith@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

#### what if there is lot of columns and we only want to change some values. such as lastname and email

In [79]:
## To do that..
df.loc[1, ['Lastname','email']] = ['Aflex', 'ben@gmail.com']

In [80]:
df

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

In [81]:
### To change a single value

df.loc[2,'Firstname'] = 'Maya'

In [82]:
df

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2      Maya      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

In [83]:
### Another method to change a single value in a row

df.at[2,'Firstname'] = 'Gin'

In [84]:
df

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk      Rob  husk1@gmail.com

In [85]:
# for instance you have email details and you need the lastname or firstname of this column
filt = (df['email'] == 'husk1@gmail.com')
df[filt]['Lastname']

3    Rob
Name: Lastname, dtype: object

In [90]:
filt = (df['email'] == 'jack@gmail.com')
df[filt]['Lastname']

0    Rob
Name: Lastname, dtype: object

In [ ]:
#### common mistakes or error when changing a single value and forget to use "loc" or "at" function

In [92]:
filt = (df['email'] == 'husk1@gmail.com')
df[filt]['Lastname'] = 'smith'   ### This will give error message.

C:\Users\lenovo pc\AppData\Local\Temp\ipykernel_3744\527000160.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[filt]['Lastname'] = 'smith'


In [93]:
### you can instead do it this way...
filt = (df['email'] == 'husk1@gmail.com')
df.loc[filt,'Lastname'] = 'smith'

In [94]:
df

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk    smith  husk1@gmail.com

In [ ]:
### How to update multiple rows of data
### let assumes we want to change all email addresses of the dataframe to be upper case

In [96]:
df['email'].str.upper() 

0     JACK@GMAIL.COM
1      BEN@GMAIL.COM
2      GIN@GMAIL.COM
3    HUSK1@GMAIL.COM
Name: email, dtype: object

In [98]:
df                       #### it did not actually change it in the dataframe

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk    smith  husk1@gmail.com

In [99]:
#### instead we can change it

df['email'] = df['email'].str.upper()

In [100]:
df

Firstname Lastname            email
0      Jack      Rob   JACK@GMAIL.COM
1       Ben    Aflex    BEN@GMAIL.COM
2       Gin      Rob    GIN@GMAIL.COM
3      Husk    smith  HUSK1@GMAIL.COM

In [101]:
### To change the entire email to lower case in the dataframe

df['email'] = df['email'].str.lower()

In [102]:
df

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk    smith  husk1@gmail.com

In [ ]:
### some other methods are: "map", "apply", "applymap","replace"


In [103]:
## "apply" is used for calling a function on a value. "apply" can work on dataframe or series object.
#let see how "apply" work on a series.

df['email'].apply(len)

0    14
1    13
2    13
3    15
Name: email, dtype: int64

In [104]:
### write simple function to update email from lower to upper

def update_email(email):
    return email.upper()

In [105]:
df['email'].apply(update_email)

0     JACK@GMAIL.COM
1      BEN@GMAIL.COM
2      GIN@GMAIL.COM
3    HUSK1@GMAIL.COM
Name: email, dtype: object

In [ ]:
### As you can see. it did not change it in the dataframe.

In [106]:
## instead we can do it this way..
df['email'] = df['email'].apply(update_email)

In [107]:
df

Firstname Lastname            email
0      Jack      Rob   JACK@GMAIL.COM
1       Ben    Aflex    BEN@GMAIL.COM
2       Gin      Rob    GIN@GMAIL.COM
3      Husk    smith  HUSK1@GMAIL.COM

In [108]:
            #OR
### to return the email back to lower
df['email'] = df['email'].apply(lambda x: x.lower())

In [109]:
df

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk    smith  husk1@gmail.com

In [ ]:
#### Let see how "apply" work on dataframe

In [110]:
df['email'].apply(len)

0    14
1    13
2    13
3    15
Name: email, dtype: int64

In [122]:
df.apply(len, axis='columns')  #### this counting by rows using ('columns as axis')

0    3
1    3
2    3
3    3
dtype: int64

In [123]:
len(df['email'])    #### this counting columns

4

In [124]:
len(df['Lastname'])  #### this counting columns

4

In [125]:
df.apply(pd.Series.min)   #### this code would have been better if use on numerical data.

Firstname              Ben
Lastname             Aflex
email        ben@gmail.com
dtype: object

In [126]:
df.apply(lambda x: x.min()) ### same result. But it's better on numerical value

Firstname              Ben
Lastname             Aflex
email        ben@gmail.com
dtype: object

In [127]:
df

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk    smith  husk1@gmail.com

In [ ]:
### "applymap only work on dataframe". its apply to every individual element in the dataframe.

In [128]:
df.applymap(len)

Firstname  Lastname  email
0          4         3     14
1          3         5     13
2          3         3     13
3          4         5     15

In [129]:
### if i want all the value in dataframe to be lower case using "applymap" note if you have numerical
### value in dataframe, it will give error message becos of the "str"

df.applymap(str.lower)

Firstname Lastname            email
0      jack      rob   jack@gmail.com
1       ben    aflex    ben@gmail.com
2       gin      rob    gin@gmail.com
3      husk    smith  husk1@gmail.com

In [ ]:
### let's check on "map" method. "map" method only work on a series, it is used for subtituting each values
### on a series with another value

In [132]:
### example: To subtitles some of the firstname.

df['Firstname'].map({'Jack':'john','Ben':'benedict'})

0        john
1    benedict
2         NaN
3         NaN
Name: Firstname, dtype: object

In [ ]:
### But "replace" method would be better inorder to avoid "NaN" that is in the output.

In [133]:
df['Lastname'].map({'Aflex':'Akins','smith':'Maya'})

0      NaN
1    Akins
2      NaN
3     Maya
Name: Lastname, dtype: object

In [ ]:
### But "replace" method would be better inorder to avoid "NaN" that is in the output.

In [ ]:
### let's check on "replace" method. "replace" method only work on a series, it is used for subtituting each values
### on a series with another value

In [135]:
df


Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1       Ben    Aflex    ben@gmail.com
2       Gin      Rob    gin@gmail.com
3      Husk    smith  husk1@gmail.com

In [136]:
df['Firstname'].replace({'Ben':'Blade','Gin':'Joy'})  ### the output is in Series

0     Jack
1    Blade
2      Joy
3     Husk
Name: Firstname, dtype: object

In [137]:
## Note, those changes does not have effect on the dataframe but if we want it to have effect
## then we can do it this way...

df['Firstname'] = df['Firstname'].replace({'Ben':'Blade','Gin':'Joy'})

In [138]:
df

Firstname Lastname            email
0      Jack      Rob   jack@gmail.com
1     Blade    Aflex    ben@gmail.com
2       Joy      Rob    gin@gmail.com
3      Husk    smith  husk1@gmail.com

##### Add/Remove Columns From DataFrames

In [140]:
### let's look at adding columns. exple, we want to combine firstname and lastname column and name it
### as firstname.

df['Firstname'] + ' ' + df['Lastname']

0       Jack Rob
1    Blade Aflex
2        Joy Rob
3     Husk smith
dtype: object

In [141]:
### To add this new join names in seperate column in the dataframe..

df['Full_Name'] = df['Firstname'] + ' ' + df['Lastname']

In [142]:
df

Firstname Lastname            email    Full_Name
0      Jack      Rob   jack@gmail.com     Jack Rob
1     Blade    Aflex    ben@gmail.com  Blade Aflex
2       Joy      Rob    gin@gmail.com      Joy Rob
3      Husk    smith  husk1@gmail.com   Husk smith

In [143]:
#### Now let's look at removing column. let assume we want to remove Firstname and Lastname column.

df.drop(columns=['Firstname','Lastname'])


email    Full_Name
0   jack@gmail.com     Jack Rob
1    ben@gmail.com  Blade Aflex
2    gin@gmail.com      Joy Rob
3  husk1@gmail.com   Husk smith

In [144]:
### as you aware that above changes has not yet have effect on dataframe but if we want it to be effective
### "inplace" function is required

df.drop(columns=['Firstname','Lastname'], inplace=True)


In [145]:
df

email    Full_Name
0   jack@gmail.com     Jack Rob
1    ben@gmail.com  Blade Aflex
2    gin@gmail.com      Joy Rob
3  husk1@gmail.com   Husk smith

In [146]:
### To reverse this or to seperate our Full_Name column..

df['Full_Name'].str.split(' ')

0       [Jack, Rob]
1    [Blade, Aflex]
2        [Joy, Rob]
3     [Husk, smith]
Name: Full_Name, dtype: object

In [147]:
### inorder to make above into two different column, "expand" argument is require

df['Full_Name'].str.split(' ', expand=True)

0      1
0   Jack    Rob
1  Blade  Aflex
2    Joy    Rob
3   Husk  smith

In [148]:
### Now we need to set two column in our dataframe to these two column that just returned.
### we passed two list "[[]]" cos we are accessing multiple column
df[['Firstname','Lastname']] = df['Full_Name'].str.split(' ', expand=True)

In [149]:
df

email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith

#### adding  rows from data/dataframe

In [152]:
###let's look at adding a single row of data...we can use append method

df.append({'Firstname':'Tony','Lastname':'Babra'}, ignore_index=True)

C:\Users\lenovo pc\AppData\Local\Temp\ipykernel_3744\3403197595.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append({'Firstname':'Tony','Lastname':'Babra'}, ignore_index=True)


email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith
4              NaN          NaN      Tony    Babra

In [ ]:
### "NaN" means "Not a Number" which is use for missing value

In [ ]:
### To add a dataframe to existing dataframe..

In [162]:
people = {'Full_Name':['Tom Raj','Bidin Afro','Gem Rem'],'Firstname':['Tom','Bidin','Gem'],
         'Lastname':['Raj','Afro','Rem']
         
    
    
    
    
}

df2=pd.DataFrame(people)

In [163]:
df2

Full_Name Firstname Lastname
0     Tom Raj       Tom      Raj
1  Bidin Afro     Bidin     Afro
2     Gem Rem       Gem      Rem

In [176]:
#### let say we want to join this new dataframe to existing dataframe. note both dataframe column are 
### not inorder and they have conflicting indexes. therefore we need to ignore_index just like before.

df.append(df2,ignore_index=True)

C:\Users\lenovo pc\AppData\Local\Temp\ipykernel_3744\2147612749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df2,ignore_index=True)


email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith
4              NaN      Tom Raj       Tom      Raj
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

In [175]:
df

email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith

In [177]:
#### if we want above changes to have effect on the dataframe...

df=df.append(df2,ignore_index=True)

C:\Users\lenovo pc\AppData\Local\Temp\ipykernel_3744\1001494011.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(df2,ignore_index=True)


In [178]:
df

email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith
4              NaN      Tom Raj       Tom      Raj
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

##### removing rows from data/dataframe

In [ ]:
### we can achieve removing rows from the column by using "drop" function alongside with index in dataframe.

In [181]:
df.drop(index=4)

email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

In [ ]:
### But if we want effect to take place then we have to include "inplace = True"

In [182]:
df

email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith
4              NaN      Tom Raj       Tom      Raj
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

In [183]:
df.drop(index=4, inplace=True)

In [184]:
df

email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

In [186]:
##### if i want to drop all the rows where lastname is "Rob", we can pass in the indexes of those rows

df.drop(index= df[df['Lastname'] == 'Rob'].index)



email    Full_Name Firstname Lastname
1    ben@gmail.com  Blade Aflex     Blade    Aflex
3  husk1@gmail.com   Husk smith      Husk    smith
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

In [187]:
#####if i want to drop all the rows where lastname is "Rob", we can pass in the indexes of those rows

filt = df['Lastname'] == 'Rob'  #### Another method......
df.drop(index=df[filt].index)

email    Full_Name Firstname Lastname
1    ben@gmail.com  Blade Aflex     Blade    Aflex
3  husk1@gmail.com   Husk smith      Husk    smith
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

In [188]:
df

email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

In [189]:
filt = df['Firstname'] == 'Jack'
df.drop(index=df[filt].index)

email    Full_Name Firstname Lastname
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

##### Sorting Data

In [190]:
df

email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

In [191]:
#### let's assume above dataframe needed to be sorted by "Lastname"

df.sort_values(by='Lastname')       ### As you can see, "Lastname" was sorted out alphabetically.

email    Full_Name Firstname Lastname
1    ben@gmail.com  Blade Aflex     Blade    Aflex
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem
0   jack@gmail.com     Jack Rob      Jack      Rob
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith

In [192]:
### Assuming you want to sort it out by descending order.

df.sort_values(by='Lastname', ascending=False)

email    Full_Name Firstname Lastname
3  husk1@gmail.com   Husk smith      Husk    smith
0   jack@gmail.com     Jack Rob      Jack      Rob
2    gin@gmail.com      Joy Rob       Joy      Rob
6              NaN      Gem Rem       Gem      Rem
5              NaN   Bidin Afro     Bidin     Afro
1    ben@gmail.com  Blade Aflex     Blade    Aflex

In [193]:
#### Assuming you want to sort out two columns from dataframe at the same time.

df.sort_values(by=['Lastname','Firstname'], ascending=False)

email    Full_Name Firstname Lastname
3  husk1@gmail.com   Husk smith      Husk    smith
2    gin@gmail.com      Joy Rob       Joy      Rob
0   jack@gmail.com     Jack Rob      Jack      Rob
6              NaN      Gem Rem       Gem      Rem
5              NaN   Bidin Afro     Bidin     Afro
1    ben@gmail.com  Blade Aflex     Blade    Aflex

In [194]:
#### Assuming you want to sort "Lastname" column in ascending order and "Firstname" column in descending order.

df.sort_values(by=['Lastname','Firstname'], ascending=[False, True])


email    Full_Name Firstname Lastname
3  husk1@gmail.com   Husk smith      Husk    smith
0   jack@gmail.com     Jack Rob      Jack      Rob
2    gin@gmail.com      Joy Rob       Joy      Rob
6              NaN      Gem Rem       Gem      Rem
5              NaN   Bidin Afro     Bidin     Afro
1    ben@gmail.com  Blade Aflex     Blade    Aflex

In [195]:
### And if we want above effect to take place then we have to include "inplace = True"

df.sort_values(by=['Lastname','Firstname'], ascending=[False, True], inplace=True)

In [196]:
df

email    Full_Name Firstname Lastname
3  husk1@gmail.com   Husk smith      Husk    smith
0   jack@gmail.com     Jack Rob      Jack      Rob
2    gin@gmail.com      Joy Rob       Joy      Rob
6              NaN      Gem Rem       Gem      Rem
5              NaN   Bidin Afro     Bidin     Afro
1    ben@gmail.com  Blade Aflex     Blade    Aflex

In [197]:
#### To reverse dataframe back to how it was before and have those index to be sorted.

df.sort_index()

email    Full_Name Firstname Lastname
0   jack@gmail.com     Jack Rob      Jack      Rob
1    ben@gmail.com  Blade Aflex     Blade    Aflex
2    gin@gmail.com      Joy Rob       Joy      Rob
3  husk1@gmail.com   Husk smith      Husk    smith
5              NaN   Bidin Afro     Bidin     Afro
6              NaN      Gem Rem       Gem      Rem

In [198]:
#### To sort a single column in a series

df['Lastname'].sort_values()

1    Aflex
5     Afro
6      Rem
0      Rob
2      Rob
3    smith
Name: Lastname, dtype: object

##### Grouping and Aggregating - Analyzing and Exploring Your Data.

In [ ]:
#### Assuming you want to know average salary of developer or how many people from each country
### knows python or another programming language