In [3]:
import numpy as np



In [4]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([4,5,6,7],dtype='int32')
print(b)

[4 5 6 7]


In [6]:
c = np.array([[6.0,3.0,5.0,7.0],[4.0,8.0,9.0,1.0]])
print(c)

[[6. 3. 5. 7.]
 [4. 8. 9. 1.]]


In [7]:
#Get dimension
a.ndim

1

In [7]:
c.ndim

2

In [8]:
#Get shape
a.shape

(3,)

In [9]:
b.shape

(4,)

In [10]:
c.shape

(2, 4)

In [9]:
#Get type
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('int16')

In [12]:
#Get size
a.itemsize

2

In [16]:
#Get total size
a.nbytes

12

In [22]:
b.itemsize

4

In [23]:
b.nbytes

16

In [7]:
d = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [104]:
####  means (2rows, 7column)
d.shape  

(2, 7)

In [35]:
#Get a specific element [r,c]
d[1,5]  #Python indexing start with the first row(0) and first column is zero(0) and second row is (1) and second column(1)

13

In [45]:
#Get a specific row
d[0,:]   # - 0 means first row and ":" means entire row


array([1, 2, 3, 4, 5, 6, 7])

In [8]:
d[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [40]:
#Get a specific column
d[:,2]

array([ 3, 10])

In [51]:
#Get [startindex:endindex:stepsize]
d[0,1:6:2]

array([2, 4, 6])

In [56]:
d[1,5] = 20

print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [58]:
d[:,2] = [4,5]
print(d)

[[ 1  2  4  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [ ]:
*3d-example

In [61]:

e = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific element(workoutside in)

In [63]:
e[0,1,1]

4

In [102]:
e[:,1]

array([[7, 9],
       [9, 7]])

In [80]:
#replace
e[:,1,:] = [[7,9],[9,7]]
print(e)

[[[5 5]
  [7 9]]

 [[3 3]
  [9 7]]]


In [88]:
#initializing different types of arrays
#All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [98]:
np.zeros((2,3))
        

array([[0., 0., 0.],
       [0., 0., 0.]])

In [101]:
#All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
##### Any other number

np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [21]:
#### Any other number full_like

np.full_like(d,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [22]:
###### Random decimal number

np.random.rand(4,2)

array([[0.71600911, 0.02655629],
       [0.45880085, 0.25113812],
       [0.75316662, 0.06120442],
       [0.66008331, 0.42886821]])

In [23]:
np.random.rand(4,2,3)

array([[[0.11417156, 0.82019494, 0.92356257],
        [0.87369898, 0.53928511, 0.09505162]],

       [[0.83693708, 0.39743276, 0.95421718],
        [0.54255973, 0.40101351, 0.66729896]],

       [[0.92100215, 0.40392157, 0.96453128],
        [0.64347717, 0.8632735 , 0.19978399]],

       [[0.42415768, 0.94367912, 0.99705828],
        [0.29183361, 0.9602199 , 0.55930789]]])

In [29]:
###### random integer values matrix

np.random.randint(4,7, size=(3,3))

array([[4, 6, 5],
       [5, 4, 5],
       [6, 5, 4]])

In [30]:
np.random.randint(2,6, size=(2,3))

array([[4, 3, 5],
       [3, 4, 4]])

In [31]:
### Also if you want to add negative number in the matrix
np.random.randint(-2,7, size=(3,4))

array([[ 6, -2,  4, -1],
       [ 3, -1,  4,  6],
       [ 6,  5,  2, -1]])

In [32]:
#### identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
#### Repeat the array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [34]:
apz = np.array([[4,5,6]])
icon = np.repeat(apz,3, axis=0)
print(icon)

[[4 5 6]
 [4 5 6]
 [4 5 6]]


In [49]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)




[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
#### Be careful when copying arrays!!!

a = np.array([1,2,3,4])
print(a)

b = a
print(b)

b[0] = 100
print(b)

print(a)  ### here is the problem. i only modifying "b" not "a". so inorder to solve this, use "copy"
### whenever copy any array



[1 2 3 4]
[1 2 3 4]
[100   2   3   4]
[100   2   3   4]


In [58]:
a = np.array([1,2,3,4])
print(a)

b = a.copy()
print(b)

b[0] = 100
print(b)

print(a)  ### you see, unlike before. a was showing 100 also before.

[1 2 3 4]
[1 2 3 4]
[100   2   3   4]
[1 2 3 4]


In [59]:
##### Mathematics
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [60]:
a + 2

array([3, 4, 5, 6])

In [64]:
a += 2    ### it means 2 + everything inside a
print(a)

[3 4 5 6]


In [61]:
a-2

array([-1,  0,  1,  2])

In [62]:
a * 2

array([2, 4, 6, 8])

In [63]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [65]:
a//2

array([1, 2, 2, 3], dtype=int32)

In [67]:
a ** 2

array([ 9, 16, 25, 36])

In [68]:
b = np.array([5,3,4,2])  #### note a has changed to [3,4,5,6] 
a + b

array([8, 7, 9, 8])

In [69]:
#### Take the sin or cos

np.cos(b)

array([ 0.28366219, -0.9899925 , -0.65364362, -0.41614684])

In [71]:
np.sin(b)

array([-0.95892427,  0.14112001, -0.7568025 ,  0.90929743])

In [73]:
#### Linear Algebra. Note column of the first matrix should be equal to the row of the second matrix.
### to multipy two or more matrix together. use "matmul"

a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#### statistics

In [82]:
stats = np.array([[1,2,3,4],[5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [83]:
np.min(stats)

1

In [85]:
np.min(stats, axis=1)  #### it gives minimum from both sides

array([1, 5])

In [86]:
np.min(stats, axis=0)  #### it gives minimum from the entire row.

array([1, 2, 3, 4])

In [84]:
np.max(stats)

8

In [87]:
np.max(stats, axis=1)

array([4, 8])

In [88]:
np.max(stats, axis=0)

array([5, 6, 7, 8])

In [89]:
np.sum(stats)

36

In [90]:
np.sum(stats, axis=0)

array([ 6,  8, 10, 12])

In [91]:
np.sum(stats, axis=1)

array([10, 26])

In [ ]:
###### Reorganizing Arrays

In [114]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

after = before.reshape((4,2))
print(after)

after = before.reshape((2,4))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [115]:
### vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [116]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
### horizontal stack

In [119]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
##### Miscellaneous: load data from file

In [122]:
filedata = np.genfromtxt('data.txt', delimiter= ',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [125]:
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [ ]:
#### Boolean masking and Advanced Indexing

In [127]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [ ]:
#### You can index with a list in Numpy

In [129]:
a = np.array([1,2,3,4,5,6,7,8,9])

a[[1,2,8]]

array([2, 3, 9])

In [130]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [132]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [135]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [136]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [137]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [140]:
a[2:4,0:2]    ###### Assignment

array([[11, 12],
       [16, 17]])

In [141]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [144]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])